name: wine-qualit-ci
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: |
        pip install flake8
        flake8 .

  dvc-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install DVC
      run: pip install dvc-s3
    - name: Configure DVC
      run: |
        dvc pull
        ls -lh data/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-artifact
        path: |
            model/model.pkl
            model/metrics.yaml

  api-tests:
    runs-on: ubuntu-latest
    needs: dvc-check
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Download model artifact
      uses: actions/download-artifact@v4
      with:
          name: model-artifact
          path: model

    - name: Install dependencies
      run: |
          pip install -r requirements.txt
          pip install pytest

    - name: Run API tests
      run: pytest tests/